import * as stylex from "@stylexjs/stylex";
// import {Inter} from 'next/font/google'
// import {inter} from '~/app/font.ts'
import cx from "clsx";
import type { Metadata } from "next";

import "./globals.css";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: { children: React.ReactNode }) {
	return (
		// <html lang="en" {...stylex.props(styles.root)}>
		<html lang="en">
			{/* <body className={cx(inter.className, inter.variable)}>{children}</body> */}
			<body>{children}</body>
		</html>
	);
}

// const styles = stylex.create({
// 	root: {
// 		minHeight: "100vh",
// 	},
// });
