import * as stylex from '@stylexjs/stylex'
import { presets } from '@urban-ui/theme'
import cx from 'clsx'
import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'

import '@urban-ui/reset/reset.css'
import './globals.css'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const bodyStyles = stylex.props(presets.body)

  return (
    <html lang="en">
      <body
        className={cx(
          geistSans.variable,
          geistMono.variable,
          bodyStyles.className,
        )}
      >
        {children}
      </body>
    </html>
  )
}
