import { colors } from '@stylexjs/open-props/lib/colors.stylex'
import stylex from '@stylexjs/stylex'
import cx from 'clsx'
import type { Metadata } from 'next'

import './globals.css'

const styles = stylex.create({
  html: {
    colorScheme: 'light dark',
    // color: colors.orange10,
  },
  reset: {
    padding: 0,
    margin: 0,
  },
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" {...stylex.props(styles.html, styles.reset)}>
      <body>{children}</body>
    </html>
  )
}

export default RootLayout
