import cx from 'clsx'
import type { Metadata } from 'next'
import { inter, roboto } from '~/app/font.ts'

import '@urban-ui/reset/reset.css'
import './globals.css'

// @TODO can we apply a font-family to the standard global theme for urban-ui?
// This touches on how to overwrite the default theme, and then, how to swap themes?

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={cx(roboto.className, roboto.variable)}>
        <h1>Layout rendered title</h1>
        {children}
      </body>
    </html>
  )
}
