import * as stylex from '@stylexjs/stylex'
import { presets } from '@urban-ui/theme'
import { accent, tone } from '@urban-ui/theme/colors.stylex'
import { space } from '@urban-ui/theme/layout.stylex'
import cx from 'clsx'
import type { Metadata } from 'next'

import { inter, roboto } from '@/app/font'

import '@urban-ui/reset/reset.css'
import './globals.css'

// @TODO can we apply a font-family to the standard global theme for urban-ui?
// This touches on how to overwrite the default theme, and then, how to swap themes?

const styles = stylex.create({
  html: {
    backgroundColor: tone.surfaceMuted,
    color: tone.fgHi,
  },
  body: {
    padding: space[800],
  },
  bar: {
    backgroundColor: `linear-gradient(90deg, ${accent.solid}, ${accent.border})`,
    height: '4px',
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
  },
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const htmlStyles = stylex.props(styles.html)
  const bodyStyles = stylex.props(presets.body, styles.body)

  return (
    <html lang="en" className={cx(inter.variable, htmlStyles.className)}>
      <body
        className={cx(roboto.className, roboto.variable, bodyStyles.className)}
      >
        <div {...stylex.props(styles.bar)} />
        <div id="root">{children}</div>
      </body>
    </html>
  )
}
